#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

###---Autostart---###

# Status Bar
dwmblocks &

# Keyboard Layout
# 1. Set default keyboard leyout
# 2. Set both caps lock keys to toggle caps behavior
# 3. Make caps lock act as Ctrl when pressed with other key
setxkbmap -layout fr \
          -option grp:lctrl_lwin_toggle \
          -option shift:both_capslock \
          -option caps:ctrl_modifier &
# Set caps lock (single key press) behavior to be Escape
killall xcape 2>/dev/null ; xcape -e 'Caps_Lock=Escape' &

# Key Repeat Delay And Interval
xset r rate 300 50 &

# Automatic Screen-Lock
xss-lock  -- betterlockscreen -l blur &

# Compositor
picom -b &

# Anti blue light program.
redshift &

# Notification system
dunst &

# Load XResources file
xxrdb -merge $XDG_CONFIG_HOME/X11/Xresources &

# ??
xsetroot -cursor_name left_ptr &

# Program that hides the mouse after 3 seconds of idle
unclutter -idle 3 &

# Wallpaper
nitrogen --restore &
