filetype plugin indent on
syntax on
set backspace=indent,eol,start
set hidden
set noswapfile
set clipboard=unnamedplus
set cursorline

packadd! dracula
syntax enable
colorscheme dracula

set number
set number relativenumber

set termguicolors

let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

set path=.,**
set wildmenu
