#+startup: fold

*   Configuration de Doom Emacs
** Général
*** Apparance
**** Polices
Doom expose cinq variables (facultatives) pour contrôler les polices dans Doom. Ici sont les trois importantes:

#+begin_src emacs-lisp
  (setq doom-font (font-spec :family "monospace" :size 14)
        doom-variable-pitch-font (font-spec :family "sans"))
#+end_src

**** Theme
On utilisera le theme =modus-operandi= pour son jeux de couleurs finement contrasté.

#+begin_src emacs-lisp
 (setq doom-theme 'doom-one-light)
#+end_src

*** Numéros de ligne
On définit les numéros de ligne afin de pouvoir accéder à la fonctionnalité de saut par nombre de lignes du mode majeur =evil= dans Emacs. On définit ici les numéros de ligne relatives qui selon mon opinion donne un meilleur contrôle sur cette fonction.

#+begin_src emacs-lisp
 (setq display-line-numbers-type 'relative)
#+end_src

*** Profil
On définit les variables suivantes car certaines fonctionnalités l'utilisent pour nous identifier, e.g la configuration GPG, ou l'e-mail.

#+begin_src emacs-lisp
 (setq user-full-name "Lydien SANDANASAMY"
       user-mail-address "s.lydien@icloud.com")
#+end_src
*** Gestion des fenêtres
Quand on décide de créer une nouvelle fenêtre, on déplacera le curseur vers celle-ci.

#+begin_src emacs-lisp
(setq evil-split-window-below t
      evil-vsplit-window-right t)
#+end_src
** Org-mode
*** Général

Ici, on définit l'apparence du mode majeur Org, on enlève donc les modes suivants : =mode-line= , =mixed-pitched-mode=, =display-line-numbers-mode=, =visual-line-mode=, =org-indent-mode=.

#+begin_src emacs-lisp
(defun lydien/org-mode-setup ()
  (org-indent-mode)
  (visual-line-mode 1)
  (hide-mode-line-mode 1)
  (display-line-numbers-mode 0))

(defun lydien/org-mode-visual-fill ()
  (setq visual-fill-column-width 100
        visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(add-hook! org-mode
      (lydien/org-mode-setup)
      (lydien/org-mode-visual-fill))

(setq org-directory "~/MEGA/org/"
      org-archive-location (concat org-directory ".archive/%s::")
      org-roam-directory (concat org-directory "notes/")
      org-roam-db-location (concat org-roam-directory ".org-roam.db")
      org-journal-encrypt-journal t
      org-journal-file-format "%d%m%Y.org"
      org-startup-folded 'overview
      org-ellipsis " ▾" )
#+end_src

*** Org-Bullets

#+begin_src emacs-lisp
(setq org-superstar-headline-bullets-list '("◉" "○" "●" "○" "●" "○" "●"))
#+end_src

*** Org-babel

#+begin_src emacs-lisp
(require 'org-tempo)
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("sh" . "src shell"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))
#+end_src

** Dired

#+begin_src emacs-lisp
(add-hook! dired-mode 'dired-hide-details-mode)
#+end_src emacs-lisp

** Email

#+begin_src emacs-lisp
;; Each path is relative to `+mu4e-mu4e-mail-path', which is ~/.mail by default
(set-email-account! "emacs"
  '((mu4e-sent-folder       . "/emacs/Sent Mail")
    (mu4e-drafts-folder     . "/emacs/Drafts")
    (mu4e-trash-folder      . "/emacs/Trash")
    (mu4e-refile-folder     . "/emacs/All Mail")
    (smtpmail-smtp-user     . "s.lydien@gmail.com")
    (mu4e-compose-signature . "---\nLydien Sandanasamy"))
  t)
#+end_src emacs-lisp
