#+startup: fold

*   Configuration de Doom Emacs
** Général
*** Apparance
**** Polices

Doom expose cinq variables (facultatives) pour contrôler les polices dans Doom. Ici sont les trois importantes:

#+begin_src emacs-lisp
  (setq doom-font (font-spec :family "monospace" :size 16 :weight 'Regular)
        doom-big-font (font-spec :family "monospace" :size 24 :weight 'Regular)
        doom-variable-pitch-font (font-spec :family "sans" :size 20 :weight 'Regular))
#+end_src

**** Theme
On utilisera le theme Nord pour son jeux de couleurs finement contrasté.

#+begin_src emacs-lisp
 (setq doom-theme 'doom-nord)
#+end_src

*** Numéros de ligne

On définit les numéros de ligne afin de pouvoir accéder à la fonctionnalité de saut par nombre de lignes du mode majeur =evil= dans Emacs. On définit ici les numéros de ligne relatives qui selon mon opinion donne un meilleur contrôle sur cette fonction.

#+begin_src emacs-lisp
 (setq display-line-numbers-type 'relative)
#+end_src

*** Profil

On définit les variables suivantes car certaines fonctionnalités l'utilisent pour nous identifier, e.g la configuration GPG, ou l'e-mail.

#+begin_src emacs-lisp
 (setq user-full-name "Lydien SANDANASAMY"
       user-mail-address "s.lydien@icloud.com")
#+end_src
*** Gestion des fenêtres

Quand on décide de créer une nouvelle fenêtre, on déplacera le curseur vers celle-ci.

#+begin_src emacs-lisp
(setq evil-split-window-below t
      evil-vsplit-window-right t)
#+end_src
** Org-mode
*** Général

#+begin_src emacs-lisp
(defun lydien/org-mode-setup ()
  (org-indent-mode)
  (mixed-pitch-mode 1)
  (visual-line-mode 1)
  (display-line-numbers-mode 0))

(defun lydien/org-mode-visual-fill ()
  (setq visual-fill-column-width 100
        visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(add-hook! org-mode
      (load-theme 'doom-nord t)
      (custom-set-faces!
        '(outline-1 :weight Medium :height 200)
        '(outline-2 :weight Medium :height 190)
        '(outline-3 :weight Medium :height 180)
        '(outline-4 :weight Medium :height 170)
        '(outline-5 :weight Medium :height 160)
        '(outline-6 :weight Medium :height 160))
      (lydien/org-mode-setup)
      (lydien/org-mode-visual-fill))

(setq org-directory "~/MEGA/org/"
      org-archive-location (concat org-directory ".archive/%s::")
      org-roam-directory (concat org-directory "notes/")
      org-roam-db-location (concat org-roam-directory ".org-roam.db")
      org-journal-encrypt-journal t
      org-journal-file-format "%d%m%Y.org"
      org-startup-folded 'overview
      org-ellipsis " ▾" )
#+end_src

*** Org-Bullets

#+begin_src emacs-lisp
(setq org-superstar-headline-bullets-list '("◉" "○" "●" "○" "●" "○" "●"))
#+end_src
*** Org-babel
#+begin_src emacs-lisp
(require 'org-tempo)
(add-to-list 'org-structure-template-alist '("sh" . "src shell"))
(add-to-list 'org-structure-template-alist '("el" . "emacs-lisp"))
(add-to-list 'org-structure-template-alist '("py" . "python"))
#+end_src
** Ivy

On règle la position de =ivy childframe= .

#+begin_src emacs-lisp
(after! ivy-posframe
(setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display-at-window-center))))
;; (setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display-at-frame-center)))
#+end_src
